### ISSUE TITLE
Go over use cases

### ISSUE THREAD

**Issue by bnsn-dp** [bnsn-dp/4800-Grapevine#8]
Everybody who can think of one, please do so. We'll diagram and cover them all in a meeting

**Comment by bnsn-dp** [comment]
# Structure
Requirements can be summarized in a sentence like **"The program shall..."** and the logic is noted through use cases, which are formatted in tables with the following fields:
1. **Use Case Name**
2. **External Reference (XRef)** to another heading in the SRS
3. **Trigger**, or the action that the user takes to start the use case
4. **Precondition**, or the state that the app must be in for the trigger to be possible or valid
5. **Basic Path**, a step-by-step breakdown of the use case from the user's perspective
6. **Alternate Path** to cover any deviations at any of the steps along the Basic Path including missing data
7. **Postcondition**, what occurs or what is now true of the system after execution
8. **Exception Paths**, ways for the user to abort the use case prematurely
9. **Other**, for any useful information that's not covered above

**Comment by ruungles** [comment]
Lists of Use Cases:
*Damien, Mayela and Ryan brainstormed some ideas for potential use cases. We broke them into 4 categories which will be labeled below*
USERS:

- [x] Login
- [x] User Creation
- [x] Profile Creation
- [x] Home Page View
- [x] Profile Page View
- [x] Search Bar

FRIENDS:

- [x] Friend List View
- [x] Adding New Friend
- [x] Removing Friend
- [x] Blocking User
- [x] List Online Friends (Availability status)
- [x] Direct Messaging 

POSTS:

- [x] Post Image Media
- [x] Post Text Media
- [x] Post Video Media
- [x] Commenting
- [x] Repost Post
- [x] Like Post
- [x] Dislike Post
- [x] Deleting Post
- [x] Share Post to Friends
- [x] Add Community Tag to Post
- [x] Book-marking Posts

COMMUNITY

- [x] Community Creation
- [x] Community Deletion
- [x] Community Search
- [x] Join Community
- [x] Leave Community
- [x] Setting Privacy
- [x] Community Sort Filter

**Comment by bnsn-dp** [comment]
Name: Account Creation
Trigger: The User selects the Create Account button
Precondition: The User has accessed the Login page
Basic Path:

1. The system presents an account creation form with four fields: email address, username, password, and confirm password
2. The user enters information into the account creation form and selects the "Activate Account" button
3. The system checks for the validity of the provided email, sending an activation link if the email is valid, warning the user otherwise. If the email is invalid, repeat steps 1 and 2.
4. User opens the activation link and is sent to the My Account page

Postcondition: A new account is created and stored in the database and the user is logged in
Exception Paths: At any step, the user can leave the page, which will empty the forms and halt the account creation process
Other: Passwords must by at least 8 characters long, contain at least one digit, contain no whitespace, and contain at least one special character from the set [!.*-?]

**Comment by bnsn-dp** [comment]
Name: Log In
Trigger: User accessed the login page
Precondition: The User is not logged into any account
Basic Path

1. The System provides a form with two fields: Username and Password
2. The User enters information and selects the "Log In" button
3. The System checks for the information in the database and confirms whether it is correct. If the username or password do not exist in the database, inform the user that their information is incorrect, whether it was the username, password, or both, and return to step 1 without clearing the fields. If the username and password both exist, proceed.

Postcondition: The User is logged in and accessing the Home page
Exception Paths: At any step, the user can leave the page, which will empty the forms and half the log-in process

**Comment by bnsn-dp** [comment]
Name: Log Out
Trigger: User selects the logout button
Precondition: User is logged in and accessing their own Account View
Basic Path:

1. The system presents a confirmation prompt with a "Continue" button
2. The user selects the Continue Button

Postcondition: The user is logged out of their account
Exception paths: At Step 2, the User can click outside or select an exit button to leave the prompt

**Comment by bnsn-dp** [comment]
> ...
> 
>     * [x]  Login
> 
>     * [ ]  User Creation
> 
>     * [x]  Profile Creation
> 
> ...

What's the difference between user and profile creation?

**Comment by wupp1nz** [comment]
I think user creation is supposed to say user profile, i.e the profile screen and what exactly theyre able to edit/change about themselves

**Comment by bnsn-dp** [comment]
Name: View Post
Trigger: User selects a post
Precondition: The User is accessing the Home View
Basic Path:

1. The System presents a popup that displays the Post's title, caption, and media as well as three buttons for "Upvoting", "Downvoting", and "Bookmarking". The pop-up also contains a dropdown for reading comments, a field for making comments, and a button that opens a menu for Reposting, Sharing, and Deleting if the User is viewing their own post

Postcondition: The User is accessing a Post View
Exception Path: The user can press ESC or select an exit symbol to close the post and exit the Post View

**Comment by bnsn-dp** [comment]
Name: Home View
Trigger: User opens Grapevine or Logs In to their account
Precondition: The User is accessing Grapevine
Basic Path:

1. The System provides a left sidebar that displays buttons to access the Home View, Message View, Settings View, and My Account View
2. The System provides a center body headed by a search bar and composed of a linear feed of Posts from followed Users sorted by date or engagement with each Post containing buttons to Upvote, Downvote, and Save
3. The System provides a right sidebar that displays a list of active Friends and a list of joined Communities sorted by number of active Users. Below this sidebar is a button for making a post

Postcondition: The User is accessing the Home View
Exception path: Leave Blank
Other : Leave Blank

**Comment by bnsn-dp** [comment]
Use Case: Search Post, User, or Community
Trigger: User selects the Search Bar
Precondition: User is accessing the Home View or a Community View
Basic Path:

1. The System presents a field in the search bar
2. The User inputs information using flags if desired
3. The System live-updates a pop-up containing a list of returned posts, accounts, and communities that match with the User input
4. The User selects a returned post, account, or community

Postcondition: The User is accessing a Post View, Account View, or Community View
Exception path: At any point, the User can press ESC or click outside of the pop-up to exit this use case
Other: Flags such as "--acc | -a", "--post | -p", "--com | -c" can be used to filter by accounts, posts, and communities respectively. Searching from a Community view defaults to using the "-c" flag, referencing the current Community

**Comment by bnsn-dp** [comment]
Name: Account View
Trigger: The User selects an Account
Precondition: The User is accessing the Search function, on the Home View, or a Post View
Basic Path:

1. The System presents a View with the selected Account's username, a counter for their quantity of Posts, a counter for how many friends they have, a dropdown of list of Friends, and a dropdown list of joined communities. Below this information is a linear feed of the account's Posts sorted by date or engagement.
2. The System presents a button to exit this View and return to the View they were previously accessing
3. The System presents buttons to add this account as a friend, to remove this account as a friend, to block this account, and to direct message this account

Postcondition: The User is accessing an Account View
Exception Path: The User can select the button that the System presents to exit this View
Other: If the User is viewing their own Account, they have additional Buttons to make a Post, access their account settings, and Log Out

**Comment by bnsn-dp** [comment]
Name: Adding a Friend
Trigger: User selects the "Add Friend" button
Precondition: User is accessing an Account View
Basic Path:

1. The system presents a prompt asking the user for confirmation with two buttons: "Continue" and "Cancel"
2. The user selects the "Continue" button
3. The Account is sent a Friend Request
4. The Account User can choose to accept or reject the request. If they reject the request, this process terminates. Otherwise, continue

Postcondition: The Account is now a Friend and is added to the active users list in the Home View
Exception Path: At step 2, the user can instead select "Cancel" to terminate this process
Other: Leave Blank

**Comment by bnsn-dp** [comment]
Name: Accepting a Friend Request
Trigger: The User accesses the Direct Message View
Precondition: The User is logged in and has been sent a friend request
Basic Path:

1. The System presents a counter of unviewed Friend Requests and a "Review" button as a header
2. The User selects the "Review" button
3. The System presents a list of Friend Requests sent by other Accounts sorted by date with two buttons: "Accept" and "Reject" as well as an Exit button
4. The User selects "Accept"

Postcondition: The Account is now a Friend and is added to the active users list in the Home View. Their future Posts will appear in the feed of the Home View
Exception Path: At step 3, the User can press ESC or select the Exit button to terminate this process
Other: Leave Blank

**Comment by bnsn-dp** [comment]
Name: Removing a Friend
Trigger: The User selects the "Remove Friend" Button
Precondition: The User is logged in and accessing an Account View of a Friend
Basic Path:

1. The System presents a confirmation prompt with three buttons: "Continue", "Cancel", and "Exit"
2. The User selects Continue

Postcondition: The Account is removed from the active friends list on the Home View and their future Posts will no longer automatically appear in the User's Home View.
Exception Paths: At step 2, if the User selects Cancel or Exit, this process terminates
Other: This does not prevent the Account's future Posts from appear in mutual communities or search results

**Comment by bnsn-dp** [comment]
Name: Blocking an Account
Trigger: The User selects the "Block Account" Button
Precondition: The User is logged in and accessing an Account View that is not their own
Basic Path:

1. The System presents a confirmation prompt with three buttons: "Continue, "Cancel", and "Exit"
2. The User Selects Continue

Postcondition: The Account is removed as a Friend is they were Friends, but otherwise all of their Posts will no longer be visible to the User and any comments that the Account made on the User's Posts will be removed. If there were Direct Messages Between them, the channel is closed.
Exception Paths: At Step 2, if the User selects Cancel or Exit, this process terminates
Other: Leave Blank

**Comment by bnsn-dp** [comment]
Name: Rejecting a Friend Request
Trigger: The User accesses the Direct Message View
Precondition: The User is logged in and has been sent a friend request
Basic Path:

1. The System presents a counter of unviewed Friend Requests and a "Review" button as a header
2. The User selects the "Review" button
3. The System presents a list of Friend Requests sent by other Accounts sorted by date with two buttons: "Accept" and "Reject" as well as an Exit button
4. The User selects "Reject"

Postcondition: Friend Request is removed from the list of unviewed friend requests
Exception Path: At step 3, the User can press ESC or select the Exit button to terminate this process
Other: Leave Blank

**Comment by bnsn-dp** [comment]
Name: Direct Messaging
Trigger: User selects the "Message" Button
Precondition: The User is logged in and is accessing another Account's View.
Basic Path: 

1. The system presents the Message View, which contains a field in which the User can input text, a "Send" button, and an "Exit" button
2. The User composes a message and Sends the message by pressing "Enter" or selecting the "Send" Button

Postcondition: The User is accessing the Message View
Exception Path: At any point, the User can select the "Exit" button to leave the Message View
Other: Any drafted message will not be saved when the User leaves the Message View

**Comment by bnsn-dp** [comment]
Name: Make a Post
Trigger: The User selects the "Make a Post" Button
Precondition: The User is accessing the Home View or a Community View
Basic Path:

1. The system presents the Posting View, which contains a field for the Post's title, a field for the Post's caption, a field for relevant Communities, and a field for any attached media like images, audio, and video. The View also contains a "Submit" button and a "Cancel" button
2. The User inputs a Title, which is the only necessary field
3. The User optionally inputs data for the caption, relevant communities, and media
4. The User selects the "Submit" button. If they have not filled the Title field, the system warns them that they cannot submit the post without a title

Postcondition: The Post is added to the relevant Home Views of Friends and Community Views
Exception Path: At any point, the User can press ESC or select the "Cancel" button, which will terminate the process
Other: leave blank

**Comment by bnsn-dp** [comment]
Name: Deleting a Post
Trigger: User selects "Delete" from the Menu
Precondition: User is accessing a Post View for their own Post and has selected the Menu Button
Basic Path:

1. The system presents a confirmation prompt with three buttons: "Continue", "Cancel", and "Exit"
2. The User selects "Continue"
3. The system removes the Post from the database

Postcondition: The User returns to their previous View
Exception Path: At any point, the User can press ESC or select the "Cancel" button, which will terminate the process
Other: leave blank

**Comment by bnsn-dp** [comment]
Name: Commenting
Trigger: User selects the compose comment field
Preconditions: User must be logged in and accessing a Post View
Basic Path:

1. The System presents a field above a list of previously-left comments with timestamps and engagement
2. The User inputs text to the field and hits Enter
3. The System adds the comment underneath the Post

Postcondition: The User remains on the Post View
Exception Path: If the User closes the Post, the field clears itself
Other: LEave blank

**Comment by bnsn-dp** [comment]
Name: Reposting
Trigger: User selects Repost from the Engagement Menu
Precondition: User is logged in, accessing an Engagement Menu from a Post View
Basic Path:

1. The System posts a reference to this Post on the User's Account

Postcondition: The User remains on the Post View
Exception Path: leave blank
Other: leave blank

**Comment by bnsn-dp** [comment]
Name: Upvoting a Post
Trigger: The User selects the "Upvote" button
Precondition: The User is accessing a Post View or the Home View
Basic Path:

1. The System increments the engagement field in the Post Database
2. The System visually updates the Post to indicate to the User that they have upvoted the post

Postcondition: The User remains on their View
Exception Path: leave blank
Other: If the User Upvotes again, the system undoes the Basic Path

**Comment by bnsn-dp** [comment]
Name: Downvoting a Post
Trigger: The User selects the "Downvote" button
Precondition: The User is accessing a Post View or the Home View
Basic Path:

1. The System decrements the engagement field in the Post Database
2. The System visually updates the Post to indicate to the User that they have upvoted the post

Postcondition: The User remains on their View
Exception Path: leave blank
Other: If the User Downvotes again, the system undoes the Basic Path

**Comment by bnsn-dp** [comment]
Name: Share
Trigger: User selects Share from the Engagement Menu
Precondition: User is logged in, accessing an Engagement Menu from a Post View
Basic Path:

1. The System presents a popup containing the link to the Post for the User to copy and a "Copy Link" button
2. The User Presses the "Copy Link" Button
3. The System closes the popup

Postcondition: The User remains on the Post View
Exception Path: The user can click outside of the pop-up to terminate the process
Other: leave blank

**Comment by bnsn-dp** [comment]
Name: Bookmarking Posts
Trigger: User selects the Bookmark button
Precondition: User is logged in and accessing a Post View or the Home View
Basic Path:

1. The System stores a reference to the Post in the User's Account View under a "Bookmarks" button

Postcondition: User remains on the Post View
Exception Paths: leave blank
Other: leave blank

**Comment by bnsn-dp** [comment]
Name: Community Creation
Trigger: User Selects Create Community Tag
Precondition: User is accessing the List Communities View
Basic Path:

1. The system presents the Community Settings View, which contains fields for the Community Name, Description, and Icon as well as buttons for "Save Changes", "Delete Community"
2. The user inputs information to the Community Name and Description fields
3. The user optionally uploads a file to the Icon field
4. The user selects "Save Changes"
5. The system saves the community to the community database

Postcondition: The User now accesses the Community View for their created Community
Exception Paths: At any point, the User can leave the page and the system will not save the data inputted to the fields
Other: leave blank

**Comment by bnsn-dp** [comment]
Name: Community Deletion
Trigger: User selects "Delete Community"
Precondition: User is accessing Community Settings
Basic Path:

1. The system presents a confirmation prompt with three buttons: "Continue", "Cancel", and "Exit"
2. The user selects "Continue"
3. The system removes the community and instances of its tag in all Posts

Postcondition: The User is accessing the List Communities View

**Comment by bnsn-dp** [comment]
Name: Join Community
Trigger: User selects "Join Community"
Precondition: User is accessing a Community View
Basic Path:

1. If the Community is Public, then the System adds the User to the list of members in the Community database
2. If the Community is Private, then the System presents a prompt for a passcode, which the User must Input

Postcondition: The User is accessing a Community View and the Community is added to the list of communities found in the Home View's right sidebar
Exception Paths: If the community is private and the User inputs the wrong passcode, this process terminates
Other: leave blank

**Comment by bnsn-dp** [comment]
Name: View Community
Trigger: User selects a Community from the Search bar or Home View
Precondition: none
Basic Path:

1. The system presents the Community View, which contains the Community's Name, the Community's description, the Community's Icon, a count for its current active members, a count for its total members, a count for the number of Posts it is tagged in, a linear feed of Posts that tag the community, and a "Join Community" button that changes based on membership. The Community View contains a search bar and a sort/filter dropdown in the header, The Sort/Filter dropdown contains options to sort and filter posts by engagement over a specified timespan

Postcondition: The User is accessing the Community View
Exception Paths: leave blank
Other: leave blank

**Comment by bnsn-dp** [comment]
Name: Leave Community
Trigger: User selects "Leave Community"
Precondition: User is accessing a Community View
Basic Path:

1. The System removes the User from the list of members in the Community database

Postcondition: The User is accessing a Community View and the Community is removed from the list of communities found in the Home View's right sidebar
Exception Paths: leave blank
Other: leave blank
